version: "2"

services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

  registry-auth:
    image: registry:latest
    volumes:
      - "./tests/assets/htpasswd:/auth/htpasswd:ro"
    ports:
      - "6000:6000"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:6000
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
