name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test-python-docker:
    name: 'Test python-docker'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt install wait-for-it -y
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --version
          black python_docker tests --diff
          black --check python_docker tests
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8
      - name: Startup services
        run: |
          docker-compose up -d
          docker ps

          wait-for-it localhost:5000
          wait-for-it localhost:6000
      - name: Run tests
        run: |
          pytest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
