name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test-python-docker:
    name: 'Test python-docker'
    runs-on: ubuntu-latest
    services:
      registry:
        image: library/registry
        ports:
          - "5000:5000"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --version
          black python_docker --diff
          black --check python_docker
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8
      - name: Run tests
        run: |
          pytest
